modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
modId="krayscandles"
version="1.1.2"
displayName="Kray's Magic Candles"
authors="CaptainKray, Calemi"
credits="CaptainKray - Lead Programmer & Lead Artist, Calemi - Programmer & Artist, Kryto627 - Programmer"
logoFile="logo.png"
description='''
    This mod adds 12 magical candles, 17 various colored candles, 6 powerful wands, 5 magical rituals, magical runes, altars, statues, crops, candle making, and so much more!
    '''

[[dependencies.krayscandles]]
modId="calemicore"
mandatory=true
versionRange="1.0.14"
ordering="NONE"
side="BOTH"

[[dependencies.krayscandles]]
modId="patchouli"
mandatory=false
versionRange="1.18.2-67"
ordering="NONE"
side="BOTH"

[[dependencies.krayscandles]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.krayscandles]]
    modId="minecraft"
    mandatory=true
    versionRange="1.18.2"
    ordering="NONE"
    side="BOTH"
