modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
modId="krayscandles"
version="1.1.0"
displayName="Kray's Magic Candles"
authors="CaptainKray, Calemi"
credits="CaptainKray - Lead Programmer & Lead Artist, Calemi - Programmer & Artist, Kryto627 - Programmer"
logoFile="logo.png"
description='''
    This mod adds 12 magical candles, 17 various colored candles, 6 powerful wands, 5 magical rituals, magical runes, altars, statues, crops, candle making, and so much more!
    '''

[[dependencies.krayscandles]]
modId="calemicore"
mandatory=true
versionRange="1.0.0"
ordering="NONE"
side="BOTH"

[[dependencies.krayscandles]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.krayscandles]]
    modId="minecraft"
    mandatory=true
    versionRange="1.18.1"
    ordering="NONE"
    side="BOTH"
